- name: Declare a variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare a variable in another file and access it
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: access variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: accessing a variable from inv file
  hosts: all
  connection: local
  tasks:
    - name: access variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: access facts
  hosts: all
  connection: local
  tasks:
    - name: access facts
      ansible.builtin.debug:
        msg: ansible host name == {{ansible_fqdn}}

- name: register a variable
  hosts: all
  connection: local
  tasks:
    - name: run a shell command
      ansible.builtin.shell: uptime
      register: out
    - name: print out
      ansible.builtin.debug:
        msg: "{{out}}"