- name: Declare a variable at play level
  hosts: all
  connection: local
  vars:
    ABC: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{ABC}}